import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent))
import netcheck as nc


def test_registry_registers_tests():
    initial = len(nc.TESTS)

    @nc.test("TestCat", "test description", expect="PASS")
    def _dummy(ctx):
        return nc.Result("PASS", "ok")

    assert len(nc.TESTS) == initial + 1
    added = nc.TESTS[-1]
    assert added.category == "TestCat"
    assert added.description == "test description"
    assert added.expect == "PASS"
    assert added.fn is _dummy


def test_registry_info_test():
    initial = len(nc.TESTS)

    @nc.test("InfoCat", "info test description", expect=None)
    def _info(ctx):
        return nc.Result("INFO", "data")

    assert len(nc.TESTS) == initial + 1
    added = nc.TESTS[initial]
    assert added.category == "InfoCat"
    assert added.description == "info test description"
    assert added.expect is None
    assert added.fn is _info


def test_parse_host_port_tcp():
    assert nc.parse_host_port("tcp/9999") == ("tcp", 9999)


def test_parse_host_port_udp():
    assert nc.parse_host_port("udp/53") == ("udp", 53)


def test_parse_host_port_missing_proto():
    with pytest.raises(ValueError, match="expected tcp"):
        nc.parse_host_port("9999")


def test_parse_host_port_bad_proto():
    with pytest.raises(ValueError, match="expected tcp"):
        nc.parse_host_port("icmp/9999")


def test_parse_host_port_non_integer_port():
    with pytest.raises(ValueError, match="must be an integer"):
        nc.parse_host_port("tcp/abc")


def test_parse_host_port_port_too_high():
    with pytest.raises(ValueError, match="out of range"):
        nc.parse_host_port("tcp/99999")


def test_parse_host_port_port_zero():
    with pytest.raises(ValueError, match="out of range"):
        nc.parse_host_port("tcp/0")


def test_parse_resolvers_basic():
    content = "# Generated by NetworkManager\nnameserver 192.168.200.1\nnameserver 8.8.8.8\n"
    assert nc.parse_resolvers(content) == ["192.168.200.1", "8.8.8.8"]


def test_parse_resolvers_empty():
    assert nc.parse_resolvers("# no nameservers\n") == []


def test_parse_resolvers_ignores_non_nameserver_lines():
    content = "search example.com\noptions ndots:5\nnameserver 10.0.0.1\n"
    assert nc.parse_resolvers(content) == ["10.0.0.1"]


def test_parse_gateway_default_route():
    output = (
        "default via 192.168.200.1 dev eth0 proto dhcp src 192.168.200.42 metric 100\n"
        "192.168.200.0/24 dev eth0 proto kernel scope link src 192.168.200.42\n"
    )
    assert nc.parse_gateway(output) == "192.168.200.1"


def test_parse_gateway_no_default():
    output = "192.168.200.0/24 dev eth0 proto kernel scope link src 192.168.200.42\n"
    assert nc.parse_gateway(output) is None


def test_parse_vm_ips_basic():
    output = """\
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500
    link/ether 52:54:00:ab:cd:ef brd ff:ff:ff:ff:ff:ff
    inet 192.168.200.42/24 brd 192.168.200.255 scope global dynamic eth0
    inet6 fe80::5054:ff:feab:cdef/64 scope link
"""
    result = nc.parse_vm_ips(output)
    assert "lo" in result
    assert "eth0" in result
    assert "192.168.200.42" in result["eth0"]
    assert "fe80::5054:ff:feab:cdef" in result["eth0"]
    assert "127.0.0.1" in result["lo"]


def test_parse_vm_ips_veth_peer_suffix():
    output = "3: veth0@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500\n    inet 10.0.0.1/30\n"
    result = nc.parse_vm_ips(output)
    assert "veth0" in result
    assert "10.0.0.1" in result["veth0"]
